datadump.location:
  author: H:\Spring Projects\Build a book tracker app (Spring Boot + Cassandra)\test-authors.txt
  works: H:\Spring Projects\Build a book tracker app (Spring Boot + Cassandra)\test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: AHDpnQJvDZfqioGyCJmdBdio
      password: nHZ+RzHtNAytwB-pAvNxBZZ_+ok,FzQcLYJByXF7iyr,GcZLlQzCqoyFbKPQHqn2qLRcm-7KEZe+vcOFgY_IMJ6GPFWrbwwMaAfjapX7C2R3ite0GxG3iZEw06lnso.a
      schema-action: recreate
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

  application:
    name: betterreads-data-loader
datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: 787267fa-f956-4b5d-9b9e-e507cfc72964-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:AHDpnQJvDZfqioGyCJmdBdio:40c7ae190f7bcf8b02fdf963e1aa7bce60942c86e3992726b8af52d69013ae21


spring.main.allow-circular-references: true

  